//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jiaheng.House2.Vote.Entityframework
{
    using Jiaheng.House2.Vote.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IPTables> IPTables { get; set; }
        public virtual DbSet<Selectobj_articles> Selectobj_articles { get; set; }
        public virtual DbSet<Selectobj_pics> Selectobj_pics { get; set; }
        public virtual DbSet<User_info> User_info { get; set; }
        public virtual DbSet<Vote_ChooseDetails> Vote_ChooseDetails { get; set; }
        public virtual DbSet<Vote_items> Vote_items { get; set; }
        public virtual DbSet<Vote_main> Vote_main { get; set; }
        public virtual DbSet<Vote_maintypes> Vote_maintypes { get; set; }
    }
}
